/**
 * The one writer of packages/fixtures/src/gates.gen.ts.
 *
 * Two recorders produce gate rows — `record-gate.mjs` from a forge run and
 * `packages/eval/scripts/record-eval.mjs` from a node one — and a second copy
 * of this merge would eventually write a file in a shape the other could not
 * read back. It reads the existing rows, replaces one, and writes them all.
 */
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
export const GATES_FILE = resolve(here, "../../fixtures/src/gates.gen.ts");

/** @param {{id: string, status: "green"|"red", tests: number, passed: number, recordedAt: string}} record */
export function writeGate(record) {
  const existing = existsSync(GATES_FILE) ? readFileSync(GATES_FILE, "utf8") : "";
  const prior = Object.fromEntries(
    [...existing.matchAll(/"(G\d)": (\{[^}]*\})/g)].map(([, id, body]) => [id, JSON.parse(body)]),
  );
  prior[record.id] = record;

  const body = Object.keys(prior)
    .sort()
    .map((id) => `  "${id}": ${JSON.stringify(prior[id])},`)
    .join("\n");

  writeFileSync(
    GATES_FILE,
    `// GENERATED by packages/contracts/scripts/gates.mjs — do not edit.\n` +
      `// A gate's status and test count are recorded from the run that produced\n` +
      `// them. A gate nobody has run is absent here, and reads as pending.\n\n` +
      `export type GateRecord = {\n` +
      `  id: string;\n  status: "green" | "red";\n  tests: number;\n  passed: number;\n  recordedAt: string;\n};\n\n` +
      `export const GATE_RUNS: Record<string, GateRecord> = {\n${body}\n};\n`,
  );
}
