/**
 * Runs G4 and writes what the search actually produced into
 * packages/fixtures/src/search.gen.ts.
 *
 * The strategy count, the draw count and how close the closest strategy came
 * to the bound are the numbers this gate exists to produce. They are figures
 * like any other, so they may not be typed by a human into a file the console
 * reads — the run writes them, and this folds them in.
 *
 * Usage: node scripts/record-search.mjs
 */
import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const contracts = resolve(here, "..");
const artifact = resolve(contracts, "out/g4-search.json");
const out = resolve(here, "../../fixtures/src/search.gen.ts");

let failed = false;
try {
  execFileSync("forge", ["test", "--match-path", "test/G4_*"], {
    cwd: contracts,
    stdio: "inherit",
    /* The search is thousands of strategies and takes minutes. A timeout
       shorter than the thing being measured would record a red gate for a
       reason that has nothing to do with the contract. */
    timeout: 30 * 60 * 1000,
  });
} catch {
  failed = true;
}

if (failed || !existsSync(artifact)) {
  console.error("the search did not finish, so nothing is recorded and the figure stays pending");
  process.exit(1);
}

const run = JSON.parse(readFileSync(artifact, "utf8"));

writeFileSync(
  out,
  `// GENERATED by packages/contracts/scripts/record-search.mjs from the G4 run\n` +
    `// itself. Do not edit: every number here is what the search produced.\n\n` +
    `export type SearchRun = {\n` +
    `  /** Named tactics multiplied by the variants each was swept through. */\n` +
    `  strategies: number;\n` +
    `  draws: number;\n` +
    `  released: number;\n` +
    `  refused: number;\n` +
    `  /** Must be zero. One that passes is a bug, not a feature. */\n` +
    `  passedABound: number;\n` +
    `  /** The most any single strategy got a root's window to, base units 6dp. */\n` +
    `  closestToBudget6: bigint;\n` +
    `  /** The bound it was measured against. */\n` +
    `  budget6: bigint;\n` +
    `  releasedAmount6: bigint;\n` +
    `  recordedAt: string;\n` +
    `};\n\n` +
    `export const SEARCH: SearchRun = {\n` +
    `  strategies: ${run.strategies},\n` +
    `  draws: ${run.draws},\n` +
    `  released: ${run.released},\n` +
    `  refused: ${run.refused},\n` +
    `  passedABound: ${run.passedABound},\n` +
    `  closestToBudget6: ${run.closestToBudget6}n,\n` +
    `  budget6: ${run.budget6}n,\n` +
    `  releasedAmount6: ${run.releasedAmount6}n,\n` +
    `  recordedAt: "${new Date().toISOString().slice(0, 10)}",\n` +
    `};\n`,
);

console.log(
  `G4: ${run.strategies} strategies, ${run.draws} draws, ${run.refused} refused, ` +
    `${run.passedABound} past a bound`,
);
