// SPDX-License-Identifier: MIT
pragma solidity 0.8.28;

// GENERATED by packages/fixtures/scripts/emit-solidity.ts — do not edit.
// Every figure here has one source: packages/fixtures/src/index.ts.

library Fixtures {
    /* Chain — USDC has two decimal views of one balance. The contracts use
       the 6-decimal ERC-20 view and never the 18-decimal native one, so no
       scaling exists in Solidity at all. scaleUsdc lives in fixtures alone. */
    uint256 internal constant CHAIN_ID = 5042002;
    address internal constant USDC = 0x3600000000000000000000000000000000000000;
    uint8 internal constant USDC_DECIMALS = 6;
    uint8 internal constant NATIVE_DECIMALS = 18;

    /* The demo mandate. Every field is a bound the contract evaluates. */
    uint128 internal constant BUDGET6 = 100000000;
    uint64 internal constant WINDOW_SECONDS = 86400;
    uint8 internal constant MAX_DEPTH = 3;
    uint128 internal constant TRANCHE6 = 5000000;
    uint16 internal constant CONCENTRATION_BPS = 3500;

    /* ERC-8004 — live on Arc already. Nothing to deploy. */
    address internal constant IDENTITY_REGISTRY = 0x8004A818BFB912233c491871b3d84c89A494BD9e;
    address internal constant REPUTATION_REGISTRY = 0x8004B663056A597Dffe9eCcC1965A193B7388713;

    /* Circle's GatewayWallet on Arc. Verified by eth_getCode and by reaching
       depositFor's allowance check on 2026-09-08. */
    address internal constant GATEWAY_WALLET = 0x0077777d7EBA4688BDeF3E311b846F25870A19B9;

    /* Structuring beat: 10000 calls at $0.008
       to one payee is $80. Every call is under any
       per-transfer cap; the concentration bound is what refuses it. */
    uint256 internal constant STRUCTURING_CALLS = 10000;
    uint128 internal constant STRUCTURING_UNIT6 = 8000;
}
