/**
 * Emits the ABIs the daemon calls, from the artifacts forge just built.
 *
 * An ABI copied by hand is the same defect as a figure written twice: it goes
 * stale the first time a signature changes, and the failure is a decode error
 * at runtime rather than a type error at build. So this reads
 * packages/contracts/out and writes one generated file.
 */
import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const contracts = resolve(here, "../../contracts");
const out = resolve(here, "../src/abi.gen.ts");

const WANTED = ["TreeVault", "MandateRegistry", "ConductRecord", "IERC20", "IGatewayWallet"];

const artifact = (name) => resolve(contracts, `out/${name}.sol/${name}.json`);
if (!WANTED.every((n) => existsSync(artifact(n)))) {
  execFileSync("forge", ["build"], { cwd: contracts, stdio: "inherit" });
}

let body = "";
for (const name of WANTED) {
  const { abi } = JSON.parse(readFileSync(artifact(name), "utf8"));
  body += `export const ${name}Abi = ${JSON.stringify(abi, null, 2)} as const;\n\n`;
}

writeFileSync(
  out,
  "// GENERATED by packages/daemon/scripts/emit-abi.mjs from the forge\n" +
    "// artifacts in packages/contracts/out. Do not edit; run `npm run abi`.\n\n" +
    body,
);
console.log(`abi -> ${out}`);
