/**
 * Emits the ABIs the daemon calls, from the artifacts forge just built.
 *
 * An ABI copied by hand is the same defect as a figure written twice: it goes
 * stale the first time a signature changes, and the failure is a decode error
 * at runtime rather than a type error at build. So this reads
 * packages/contracts/out and writes one generated file.
 */
import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const contracts = resolve(here, "../../contracts");
const out = resolve(here, "../src/abi.gen.ts");

const WANTED = ["TreeVault", "MandateRegistry", "ConductRecord", "IERC20", "IGatewayWallet"];

const artifact = (name) => resolve(contracts, `out/${name}.sol/${name}.json`);
const built = WANTED.every((n) => existsSync(artifact(n)));

/**
 * Build the artifacts, unless there is nothing to build them with.
 *
 * `abi.gen.ts` is committed so that every suite and typecheck that needs no
 * chain also needs no Foundry — that is the split the `units` job exists to
 * keep honest. This script sat inside `npm run build`, so a typecheck on a
 * clean checkout found no `out/` (it is gitignored), shelled out to `forge`,
 * and died with ENOENT on a runner that had deliberately not installed it.
 *
 * So a missing toolchain is only fatal when there is also nothing committed
 * to fall back to. When both are missing the error says which is which,
 * rather than printing a spawn failure about a binary the reader may not know
 * this script wanted. Whether the committed copy is still correct is not this
 * script's question: the job with a compiler regenerates it and fails on a
 * diff.
 */
if (!built) {
  const forge = (() => {
    try {
      execFileSync("forge", ["build"], { cwd: contracts, stdio: "inherit" });
      return true;
    } catch (error) {
      if (error?.code !== "ENOENT") throw error;
      return false;
    }
  })();

  if (!forge) {
    if (existsSync(out)) {
      console.log(`abi -> kept ${out} (no forge, no artifacts)`);
      process.exit(0);
    }
    console.error(
      "no forge on PATH and no artifacts in packages/contracts/out, and " +
        "src/abi.gen.ts has not been committed either — install Foundry or " +
        "run this where the contracts have been built.",
    );
    process.exit(1);
  }
}

let body = "";
for (const name of WANTED) {
  const { abi } = JSON.parse(readFileSync(artifact(name), "utf8"));
  body += `export const ${name}Abi = ${JSON.stringify(abi, null, 2)} as const;\n\n`;
}

writeFileSync(
  out,
  "// GENERATED by packages/daemon/scripts/emit-abi.mjs from the forge\n" +
    "// artifacts in packages/contracts/out. Do not edit; run `npm run abi`.\n\n" +
    body,
);
console.log(`abi -> ${out}`);
