/**
 * Emits the tool list the site renders, from the server that declares it.
 *
 * The site used to carry its own copy: `cordon_spawn(label, cap)`, an argument
 * list the server has never had. A page describing a tool nobody can call is
 * the same defect as a figure written twice, and this project has already
 * decided how it handles those.
 *
 * So the list is introspected out of a live server over the real protocol —
 * not read off the source, which could describe a tool that fails to register.
 *
 * Run: node packages/mcp/scripts/emit-tools.ts
 */
import { writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { Client } from "@modelcontextprotocol/sdk/client/index.js";
import { InMemoryTransport } from "@modelcontextprotocol/sdk/inMemory.js";
import type { Hex } from "viem";
import { createMcpServer } from "../src/server.ts";
import { ABSENT_TOOLS } from "../src/tools.ts";
import { ENV } from "../../daemon/src/config.ts";
import { ARC } from "../../fixtures/src/index.ts";
import type { Gate } from "../../daemon/src/gate.ts";

const here = dirname(fileURLToPath(import.meta.url));
const out = resolve(here, "../../fixtures/src/tools.gen.ts");

/* The server is asked what it exposes; it is never asked to do anything, so a
   gate that answers nothing is enough. */
const gate = {
  nodes: () => [],
  headroom: async () => ({ available: 0n, boundBy: "0x" }),
  mandate: async () => ({}),
} as unknown as Gate;

const server = createMcpServer({
  gate,
  settler: { async settle() { throw new Error("not called"); } },
  acceptable: { networks: [], assets: [] },
  node: "0x" as Hex,
});

const client = new Client({ name: "emit-tools", version: "0" });
const [clientSide, serverSide] = InMemoryTransport.createLinkedPair();
await Promise.all([server.connect(serverSide), client.connect(clientSide)]);

const { tools } = await client.listTools();

const entries = tools
  .map((tool) => {
    const schema = (tool.inputSchema ?? {}) as {
      properties?: Record<string, { description?: string }>;
      required?: string[];
    };
    const required = new Set(schema.required ?? []);
    const args = Object.keys(schema.properties ?? {})
      .map((name) => (required.has(name) ? name : `${name}?`))
      .join(", ");
    return {
      name: tool.name,
      args: args || "no arguments",
      note: (tool.description ?? "").replace(/\s+/g, " ").trim(),
    };
  })
  .sort((a, b) => a.name.localeCompare(b.name));

writeFileSync(
  out,
  `// GENERATED by packages/mcp/scripts/emit-tools.ts, by asking a running\n` +
    `// server what it exposes. Do not edit. A tool that fails to register\n` +
    `// disappears from here, which is the point.\n\n` +
    `export const MCP_TOOLS = ${JSON.stringify(entries, null, 2)} as const;\n\n` +
    `/** The tools that will never exist. The absence is the argument, and it\n` +
    ` *  is asserted against the same server in packages/mcp/test. */\n` +
    `export const ABSENT_TOOLS = ${JSON.stringify([...ABSENT_TOOLS], null, 2)} as const;\n\n` +
    `/** The block to paste into an MCP client. Its environment is the one the\n` +
    ` *  daemon actually reads — see ENV in packages/daemon/src/config.ts. */\n` +
    `export const MCP_CONFIG = ${JSON.stringify(configBlock(), null, 2)};\n\n` +
    `export const MCP_ENV = ${JSON.stringify(ENV, null, 2)} as const;\n`,
);

/** Built from what the daemon requires, so it cannot describe a variable no
 *  code reads — which is what both hand-written versions of this did. */
function configBlock(): string {
  const env: Record<string, string> = {};
  for (const name of Object.keys(ENV.required)) {
    env[name.replace("<label>", "ME")] = name.startsWith("CORDON_KEY") ? "…" : "0x…";
  }
  env.CORDON_RPC = ARC.rpc;

  return JSON.stringify(
    { mcpServers: { cordon: { command: "npx", args: ["-y", "@cordon/mcp"], env } } },
    null,
    2,
  );
}

console.log(`tools -> ${out}`);
for (const entry of entries) console.log(`  ${entry.name}(${entry.args})`);
await client.close();
