/**
 * Emits the Solidity view of `packages/fixtures`.
 *
 * The rule is that every figure has exactly one source. Solidity cannot import
 * TypeScript, so the choice is to write each number twice or to generate one
 * from the other. Written twice, they drift — that is the defect class this
 * project has already paid for elsewhere. So the tests read a generated file,
 * and the generated file is checked in so a reader can see what the tests
 * asserted without running a build.
 *
 * Run: node packages/fixtures/scripts/emit-solidity.ts
 */

import { writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { ARC, MANDATE, ERC8004, STRUCTURING } from "../src/index.ts";

const here = dirname(fileURLToPath(import.meta.url));
const out = resolve(here, "../../contracts/test/Fixtures.gen.sol");

const src = `// SPDX-License-Identifier: MIT
pragma solidity 0.8.28;

// GENERATED by packages/fixtures/scripts/emit-solidity.ts — do not edit.
// Every figure here has one source: packages/fixtures/src/index.ts.

library Fixtures {
    /* Chain — USDC has two decimal views of one balance. The contracts use
       the 6-decimal ERC-20 view and never the 18-decimal native one, so no
       scaling exists in Solidity at all. scaleUsdc lives in fixtures alone. */
    uint256 internal constant CHAIN_ID = ${ARC.chainId};
    address internal constant USDC = ${ARC.erc20};
    uint8 internal constant USDC_DECIMALS = ${ARC.erc20Decimals};
    uint8 internal constant NATIVE_DECIMALS = ${ARC.nativeDecimals};

    /* The demo mandate. Every field is a bound the contract evaluates. */
    uint128 internal constant BUDGET6 = ${MANDATE.budget6};
    uint64 internal constant WINDOW_SECONDS = ${MANDATE.windowSeconds};
    uint8 internal constant MAX_DEPTH = ${MANDATE.maxDepth};
    uint128 internal constant TRANCHE6 = ${MANDATE.tranche6};
    uint16 internal constant CONCENTRATION_BPS = ${MANDATE.concentrationBoundPct * 100};

    /* ERC-8004 — live on Arc already. Nothing to deploy. */
    address internal constant IDENTITY_REGISTRY = ${ERC8004.identity};
    address internal constant REPUTATION_REGISTRY = ${ERC8004.reputation};

    /* Structuring beat: ${STRUCTURING.calls} calls at $${STRUCTURING.unitPrice}
       to one payee is $${STRUCTURING.total}. Every call is under any
       per-transfer cap; the concentration bound is what refuses it. */
    uint256 internal constant STRUCTURING_CALLS = ${STRUCTURING.calls};
    uint128 internal constant STRUCTURING_UNIT6 = ${Math.round(STRUCTURING.unitPrice * 1e6)};
}
`;

mkdirSync(dirname(out), { recursive: true });
writeFileSync(out, src);
console.log(`fixtures -> ${out}`);
