/**
 * `cordon init` — make the operator keys where they are going to live.
 *
 * The setup this replaces was: install Foundry, run `cast wallet new` once per
 * node, copy each private key into an environment variable by hand, and paste
 * each address into a web form. Four steps, and three of them are places for a
 * key to be leaked or a value to be pasted into the wrong field.
 *
 * The daemon is the only thing that ever needs an operator key, so the daemon
 * makes it. A key is generated where it will be used and is written once, to a
 * file only its owner can read. **No private key is ever printed.** What the
 * user copies is addresses, which are public and safe to paste anywhere.
 *
 * It writes an env file rather than a format of its own, because the daemon
 * already reads `CORDON_KEY_<label>` from the environment and a second way of
 * holding a key is a second thing that can hold it wrongly.
 */
import { chmodSync, existsSync, mkdirSync, writeFileSync } from "node:fs";
import { dirname } from "node:path";
import { generatePrivateKey, privateKeyToAccount } from "viem/accounts";
import type { Address, Hex } from "viem";

export interface Operator {
  /** The label the daemon's env vars are suffixed with. */
  label: string;
  address: Address;
}

export interface InitResult {
  path: string;
  operators: Operator[];
}

/** Uppercase, because `CORDON_KEY_<label>` is read by exact name. */
export const labelFor = (index: number, total: number): string =>
  total === 1 ? "ROOT" : index === 0 ? "ROOT" : `WORKER${index}`;

/**
 * Writes the env file and returns only what is safe to show.
 *
 * `generate` is injectable so a test can assert the file holds the key it was
 * given, rather than asserting that two random values are equal.
 */
export function initOperators(options: {
  path: string;
  nodes: number;
  force?: boolean;
  generate?: () => Hex;
}): InitResult {
  const { path, nodes } = options;
  /* `Number.isInteger` and not `nodes < 1`: `Number("abc")` is NaN, every
     comparison against NaN is false, and the guard let it through — the loop
     then ran zero times and wrote a file with no keys in it. With `--force`
     that silently replaced a live tree's operators with nothing. */
  if (!Number.isInteger(nodes) || nodes < 1 || nodes > 16) {
    /* `String` and not `JSON.stringify`: NaN serialises to `null`, which
       reads as though nothing was passed rather than as something unparseable. */
    throw new Error(`--nodes must be a whole number between 1 and 16, got ${String(nodes)}`);
  }
  if (existsSync(path) && !options.force) {
    /* Overwriting is how someone loses the key an open mandate names, and the
       mandate cannot be repointed — its operator is set at `open`. */
    throw new Error(
      `${path} already exists. Keys there may be the operator of a live mandate; ` +
        `pass --force only if you are certain none of them is.`,
    );
  }

  const generate = options.generate ?? generatePrivateKey;
  const operators: Operator[] = [];
  const lines = [
    "# GENERATED by `cordon init`. Private keys — never commit this file,",
    "# never paste its contents anywhere. The addresses are the public half",
    "# and are the only part anyone else needs.",
    "#",
    "# CORDON_NODE_<label> is filled in after the owner opens the mandate for",
    "# that operator; a daemon with a key and no node id refuses to start,",
    "# which is the direction that fails safely.",
    "",
  ];

  for (let index = 0; index < nodes; index++) {
    const label = labelFor(index, nodes);
    const key = generate();
    const account = privateKeyToAccount(key);
    operators.push({ label, address: account.address });
    lines.push(`CORDON_KEY_${label}=${key}`);
    lines.push(`CORDON_NODE_${label}=`);
    lines.push("");
  }

  mkdirSync(dirname(path), { recursive: true, mode: 0o700 });
  writeFileSync(path, `${lines.join("\n")}`, { mode: 0o600 });
  /* `writeFileSync`'s mode is masked by the process umask, and an operator key
     readable by the group is the whole point of this file being one file. */
  chmodSync(path, 0o600);

  return { path, operators };
}
