// GENERATED by packages/contracts/scripts/record-addresses.mjs from
// packages/contracts/deployments/<chainId>.json. Do not edit: an address
// typed here is one that can disagree with the chain it names.

export type Deployment = {
  chainId: number;
  /** MandateRegistry. */
  registry: string;
  /** TreeVault, the only funding source. */
  vault: string;
  /** ConductRecord, which writes into the ERC-8004 reputation registry. */
  record: string;
  /** The block the contracts were made in. Reading from zero fails on
   *  Arc — the RPC answers `pruned history unavailable` — so anything
   *  that queries logs starts here, including the browser. */
  fromBlock: string;
  /** The commit the deploy script ran from. */
  commit: string;
  deployedAt: string;
};

export const DEPLOYMENT: Deployment | null = {
  chainId: 11155111,
  registry: "0x4542b831854bb9d1b3133269784b13c2d39545a1",
  vault: "0xd6ea46d29df179f607e628fc49e8d6ec4b947ee8",
  record: "0x779fbd573212532513a6773561f785094f212ac9",
  fromBlock: "11788360",
  commit: "025e0ea7df65e84ee6227d6cb400312ebe4fb482",
  deployedAt: "2026-09-26T19:48:49.698Z",
};

/** Every chain Cordon is deployed on, keyed by chain id. */
export const DEPLOYMENTS: Record<number, Deployment> = {
  5042002: {
    chainId: 5042002,
    registry: "0xf86de085e63b00c9fba300b19807c883deb961e9",
    vault: "0x00ab57acd260c594a661b6101bdf7e92267af135",
    record: "0x2a8361ac23f5ffcfde9f0d7bc7618178770332d0",
    fromBlock: "61265318",
    commit: "ee3955b82fb0b6f7786bbfb5b2f5ebc2b174f8cc",
    deployedAt: "2026-09-09T17:24:22.882Z",
  },
  11155111: {
    chainId: 11155111,
    registry: "0x4542b831854bb9d1b3133269784b13c2d39545a1",
    vault: "0xd6ea46d29df179f607e628fc49e8d6ec4b947ee8",
    record: "0x779fbd573212532513a6773561f785094f212ac9",
    fromBlock: "11788360",
    commit: "025e0ea7df65e84ee6227d6cb400312ebe4fb482",
    deployedAt: "2026-09-26T19:48:49.698Z",
  },
};
