// GENERATED by packages/contracts/scripts/record-addresses.mjs from
// packages/contracts/deployments/<chainId>.json. Do not edit: an address
// typed here is one that can disagree with the chain it names.

export type Deployment = {
  chainId: number;
  /** MandateRegistry. */
  registry: string;
  /** TreeVault, the only funding source. */
  vault: string;
  /** ConductRecord, which writes into the ERC-8004 reputation registry. */
  record: string;
  /** The commit the deploy script ran from. */
  commit: string;
  deployedAt: string;
};

export const DEPLOYMENT: Deployment | null = {
  chainId: 5042002,
  registry: "0xa50d9454e71acf152399c872815ae6895cb53229",
  vault: "0x045b2050aadaff4b80a2325d63648c09f15ab1f3",
  record: "0x12d15135b5bba8eef0d1098aa65a15af503d09c9",
  commit: "327bb926ebdfca97ed1c4d8d6c92a72701acc5f7",
  deployedAt: "2026-09-08T18:08:35.566Z",
};
