// GENERATED by packages/daemon/scripts/record-g3.mjs — do not edit.
// G3 publishes its number whichever way it came out. A drill nobody has
// run leaves this file absent, and the page says so.

export interface DrillRefusal {
  id: string;
  reason: string;
  node: string;
  breachedAt: string;
  tx: string;
}

export interface DrillRun {
  recordedAt: string;
  node: string;
  authorised6: bigint;
  lifetimeCap6: bigint;
  trancheCap6: bigint;
  spent6: bigint;
  requests: number;
  nodesInSubtree: number;
  refusals: DrillRefusal[];
}

export const DRILL_RUN: DrillRun = {
  recordedAt: "2026-09-10T20:56:30.337Z",
  node: "0x92d7ae3dbcc740cdcdc5fb8cd911fc9bebcbd35b742e5d517941f8660d51d6de",
  authorised6: 20000n,
  lifetimeCap6: 20000n,
  trancheCap6: 1000n,
  spent6: 7000n,
  requests: 9,
  nodesInSubtree: 1,
  refusals: [
    {
      "id": "6",
      "reason": "concentration",
      "node": "0x92d7ae3dbcc740cdcdc5fb8cd911fc9bebcbd35b742e5d517941f8660d51d6de",
      "breachedAt": "0x92d7ae3dbcc740cdcdc5fb8cd911fc9bebcbd35b742e5d517941f8660d51d6de",
      "tx": "0x425071b1d6af400d5b2efb8d228a60dea1b3608655212872ef27c7bc5ec4e822"
    },
    {
      "id": "7",
      "reason": "concentration",
      "node": "0x92d7ae3dbcc740cdcdc5fb8cd911fc9bebcbd35b742e5d517941f8660d51d6de",
      "breachedAt": "0x92d7ae3dbcc740cdcdc5fb8cd911fc9bebcbd35b742e5d517941f8660d51d6de",
      "tx": "0x81b956ff8769fe3b045edf0f3bf07ddc4893975af356abdfff7da3da17b4ecfb"
    }
  ],
};
