// GENERATED by packages/contracts/scripts/record-gate.mjs — do not edit.
// A gate's status and test count are recorded from the run that produced
// them. A gate nobody has run is absent here, and reads as pending.

export type GateRecord = {
  id: string;
  status: "green" | "red";
  tests: number;
  passed: number;
  recordedAt: string;
};

export const GATE_RUNS: Record<string, GateRecord> = {
  "G1": {"id":"G1","status":"green","tests":57,"passed":57,"recordedAt":"2026-09-08"},
};
