// GENERATED by packages/contracts/scripts/gates.mjs — do not edit.
// A gate's status and test count are recorded from the run that produced
// them. A gate nobody has run is absent here, and reads as pending.

export type GateRecord = {
  id: string;
  status: "green" | "red";
  tests: number;
  passed: number;
  recordedAt: string;
};

export const GATE_RUNS: Record<string, GateRecord> = {
  "G1": {"id":"G1","status":"green","tests":65,"passed":65,"recordedAt":"2026-09-08"},
  "G4": {"id":"G4","status":"green","tests":1,"passed":1,"recordedAt":"2026-09-08"},
  "G5": {"id":"G5","status":"green","tests":12,"passed":12,"recordedAt":"2026-09-08"},
  "G6": {"id":"G6","status":"green","tests":14,"passed":14,"recordedAt":"2026-09-08"},
  "G7": {"id":"G7","status":"green","tests":10,"passed":10,"recordedAt":"2026-09-09"},
};
