// GENERATED by packages/fixtures/scripts/record-marketplace.mjs — do not edit.
// Walked every page of Circle's x402 discovery API on 2026-09-12.
// Largest networks by offer count: eip155:8453 1304, solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp 810, eip155:137 532, eip155:84532 396, eip155:80002 396, solana:EtWTRABZaYq6iMfeYKouRu166VU2xqa1 264.

export const MARKETPLACE = {
  "discovery": "https://api.circle.com/v2/x402/discovery/resources",
  "recordedAt": "2026-09-12T21:56:16.429Z",
  "services": 1139,
  "offersTotal": 4041,
  "offersAtOrBelowOneCent": 2239,
  "priceMedian": 0.01,
  "priceMax": 200,
  "gatewayBatchedOffers": 1225,
  "arcListings": 0
} as const;
