// GENERATED by packages/contracts/scripts/record-search.mjs from the G4 run
// itself. Do not edit: every number here is what the search produced.

export type SearchRun = {
  /** Named tactics multiplied by the variants each was swept through. */
  strategies: number;
  draws: number;
  released: number;
  refused: number;
  /** Must be zero. One that passes is a bug, not a feature. */
  passedABound: number;
  /** The most any single strategy got a root's window to, base units 6dp. */
  closestToBudget6: bigint;
  /** The bound it was measured against. */
  budget6: bigint;
  releasedAmount6: bigint;
  recordedAt: string;
};

export const SEARCH: SearchRun = {
  strategies: 1200,
  draws: 45360,
  released: 33327,
  refused: 12033,
  passedABound: 0,
  closestToBudget6: 100000000n,
  budget6: 100000000n,
  releasedAmount6: 67783468046n,
  recordedAt: "2026-09-08",
};
