// GENERATED by packages/daemon/scripts/record-settlement.mjs — do not edit.
// One purchase that settled, read back from Arc. Three transactions: the draw
// the contract bounded, the Gateway release that brought the tranche into the
// operator's own balance, and the seller's own collection of the EIP-3009
// authorisation it was given. Anyone can open all three.

export interface SettledPurchase {
  recordedAt: string;
  chainId: number;
  node: string;
  operator: string;
  seller: string;
  price6: bigint;
  drawTx: string;
  drawBlock: bigint;
  mintTx: string;
  mintBlock: bigint;
  collectTx: string;
  collectBlock: bigint;
}

export const SETTLEMENT: SettledPurchase = {
  "recordedAt": "2026-09-11T15:06:03.585Z",
  "chainId": 5042002,
  "node": "0xce62536fab40faf475d24967b38348df257c3d5d6e28b45f60b19ba48f83340c",
  "operator": "0xd656A7c50E6720103989728A589fbAb648b19e0b",
  "seller": "0x3feeA28582C643f85Baf32D41adE6f1141A801F3",
  "price6": 10000n,
  "drawTx": "0x860378acb682cdf29c9256e17da9adf980d144b49f4362a6054a7eddc6edd2c2",
  "drawBlock": 61583431n,
  "mintTx": "0x296b8c881781cf2dbff6d83cc3126947da76fa3aa9e1480929351a1a8ed67555",
  "mintBlock": 61583445n,
  "collectTx": "0xc70f76f160aef7cc32518d2827357a1d9f996b3b6cc943ed56a9aed913a0f0c8",
  "collectBlock": 61583451n
};
