// GENERATED by packages/daemon/scripts/record-settlement.mjs — do not edit.
// One purchase that settled, read back from chain 11155111. Two transactions: the draw
// the contract bounded, which deposited the tranche straight into the operator's
// own wallet, and the seller's own collection of the EIP-3009 authorisation it
// was given. Anyone can open both.

export interface SettledPurchase {
  recordedAt: string;
  chainId: number;
  node: string;
  operator: string;
  seller: string;
  price6: bigint;
  drawTx: string;
  drawBlock: bigint;
  /** Absent on the direct rail, where the draw is the deposit. */
  mintTx?: string;
  mintBlock?: bigint;
  collectTx: string;
  collectBlock: bigint;
}

export const SETTLEMENT: SettledPurchase = {
  "recordedAt": "2026-09-26T20:53:55.958Z",
  "chainId": 11155111,
  "node": "0xb9bf434a26d1e06d72d4a73ea90f5980f0c90a5ee423b87031a3ead0a9328189",
  "operator": "0xFda26a517176E17F856364A599A4D5eD44CAfE43",
  "seller": "0x3feeA28582C643f85Baf32D41adE6f1141A801F3",
  "price6": 50000n,
  "drawTx": "0x00aeb76439ea1ffd43b946ded30061f25768712df5ece938614abc021276d778",
  "drawBlock": 11788679n,
  "collectTx": "0x5bccce8674617aa93f7bb471dd7690eaa6f2fdc90daa47aa128b9c0ca5ee3f3f",
  "collectBlock": 11788681n
};
