// GENERATED by packages/mcp/scripts/emit-tools.ts, by asking a running
// server what it exposes. Do not edit. A tool that fails to register
// disappears from here, which is the point.

export const MCP_TOOLS = [
  {
    "name": "cordon_fetch",
    "args": "url, method?, body?",
    "note": "Fetch a URL. If it answers 402, pay for it through Cordon and return the body. The recipient and the price come from the seller's own challenge, not from you. May return a refusal, which is final."
  },
  {
    "name": "cordon_spawn",
    "args": "label, budgetUsdc, trancheUsdc?, concentrationPct?",
    "note": "Register a child mandate under this one for a sub-agent. The child can only ever be narrower than its parent; the contract refuses a wider one whoever asks. The key for the child is held here, not by any agent."
  },
  {
    "name": "cordon_status",
    "args": "no arguments",
    "note": "What this mandate may still spend, and which node in the tree is the limit. The answer is often an ancestor rather than this node."
  }
] as const;

/** The tools that will never exist. The absence is the argument, and it
 *  is asserted against the same server in packages/mcp/test. */
export const ABSENT_TOOLS = [
  "cordon_transfer",
  "cordon_pay",
  "cordon_send",
  "cordon_withdraw",
  "cordon_approve"
] as const;

/** The block to paste into an MCP client. Its environment is the one the
 *  daemon actually reads — see ENV in packages/daemon/src/config.ts. */
export const MCP_CONFIG = "{\n  \"mcpServers\": {\n    \"cordon\": {\n      \"command\": \"node\",\n      \"args\": [\n        \"/path/to/cordon/packages/mcp/src/main.ts\"\n      ],\n      \"env\": {\n        \"CORDON_VAULT\": \"0x00ab57acd260c594a661b6101bdf7e92267af135\",\n        \"CORDON_REGISTRY\": \"0xf86de085e63b00c9fba300b19807c883deb961e9\",\n        \"CORDON_NODE_ME\": \"0x…\",\n        \"CORDON_KEY_ME\": \"…\",\n        \"CORDON_RPC\": \"https://rpc.testnet.arc.io\"\n      }\n    }\n  }\n}";

export const MCP_ENV = {
  "required": {
    "CORDON_VAULT": "TreeVault address, from deployments/<chainId>.json",
    "CORDON_REGISTRY": "MandateRegistry address, from the same file",
    "CORDON_NODE_<label>": "the mandate node this daemon acts for",
    "CORDON_KEY_<label>": "the operator key for that node. The agent never sees it"
  },
  "optional": {
    "CORDON_RECORD": "ConductRecord, from deployments/<chainId>.json. Without it, refusals are enforced but never published",
    "CORDON_IDENTITY": "ERC-8004 Identity; defaults to 0x8004A818BFB912233c491871b3d84c89A494BD9e",
    "CORDON_RPC": "defaults to https://rpc.testnet.arc.io",
    "CORDON_CHAIN_ID": "defaults to 5042002",
    "CORDON_USDC": "the 6-decimal ERC-20 view; defaults to Arc's",
    "CORDON_NETWORKS": "CAIP-2 ids this daemon will settle on",
    "CORDON_ASSETS": "assets it will pay in",
    "CORDON_PORT": "defaults to 8402",
    "CORDON_POLL_MS": "receipt polling interval; defaults to 250, matched to Arc's finality rather than to viem's 4,000"
  }
} as const;
